Southworks/fix/missing speech options
southworks/BotFramework-Composer pull request #60
Opened 2022-12-21 19:26 UTC by NahuelPerales

fixes minor #9354
## Description

The menu, when creating a new speech for a bot on composer, where missing the options 'Ignoring Speech' and 'Ignoring Non Speech'. We added the new scripts options and tested on composer.

## Screenshots
![image](https://user-images.githubusercontent.com/94375175/208984072-9f7aeed0-4758-42f9-ba91-57d77590e43c.png)

2022-12-21 19:36 UTC, erquirogasw approved these changes

2022-12-21 19:38 UTC, ceciliaavila requested changes
Please check if it's necessary to add the new values in [utils.ts](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/tools/language-servers/language-generation/src/utils.ts) file.

2022-12-22 19:37 UTC, ceciliaavila approved these changes

2022-12-23 12:00 UTC, ceciliaavila commented
/promoted 9456

2022-12-23 12:00 UTC, closed without merging