Optimize memory usage when parsing LgFiles
southworks/BotFramework-Composer pull request #78
Opened 2023-07-19 13:37 UTC by sw-joelmut

#minor

## Description
This PR reduces the memory usage when parsing the LgFiles ([lgParse.worker](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/client/src/recoilModel/parsers/workers/lgParser.worker.ts)) by adding a `MapOptimizer` to the `LgFilesCache`.
This optimizer consists of, based on a capacity limit, the process will start removing LgFile parse results to free up space from memory. Additionally, it takes into account all the references and relationships between other LgFiles.

> **Note**: The `MapOptimizer` capacity limit is set to store a maximum of 10 parsed LgFiles, this amount can be modified through code.

## Screenshots
The following image shows loading 9 bot responses with the `MapOptimizer` capacity size of 3 (for testing purposes), seeing the improvement in memory usage.
![image](https://github.com/southworks/BotFramework-Composer/assets/62260472/ba340007-d894-416e-9a72-c75d5d074b61)

2023-07-19 13:53 UTC, ceciliaavila requested changes

2023-07-19 14:19 UTC, sw-joelmut commented on Composer/packages/client/src/recoilModel/utils/mapOptimizer.ts
> +interface MapOptimizerTree<Key> {
Yea, the CI pipeline failed, and this was in the listed errors. Thanks!

2023-07-19 14:19 UTC, sw-joelmut commented
Applied feedback Ceci, Thanks!

2023-07-19 14:20 UTC, ceciliaavila approved these changes

2023-07-20 12:42 UTC, EduardoSteinmann approved these changes

2023-07-20 13:31 UTC, JhontSouth approved these changes

2023-07-21 12:52 UTC, sw-joelmut commented
/promoted 9614

2023-07-21 12:52 UTC, closed without merging